// Code generated by bin/docs from docs/openapi.json — do not edit by hand.
// Regenerate with `bin/docs`.

package main

// specResources is the CLI's whole command surface: one entry per resource
// the API routes, with the writable fields of its create/update body and
// its designed actions. Generated rather than hand-written for the same
// reason the spec itself is — a client that cannot drift from the server.
var specResources = []resourceSpec{
	{
		name: "contacts", singular: "contact", paramKey: "contact",
		ops: opList | opShow | opCreate | opUpdate | opDelete,
		fields: []fieldSpec{
			{name: "first_name", flag: "first-name", kind: fieldString},
			{name: "last_name", flag: "last-name", kind: fieldString},
			{name: "email", flag: "email", kind: fieldString},
			{name: "phone", flag: "phone", kind: fieldString},
			{name: "title", flag: "title", kind: fieldString},
			{name: "company_id", flag: "company-id", kind: fieldInt},
		},
	},
	{
		name: "companies", singular: "company", paramKey: "company",
		ops: opList | opShow | opCreate | opUpdate | opDelete,
		fields: []fieldSpec{
			{name: "name", flag: "name", kind: fieldString},
			{name: "domain", flag: "domain", kind: fieldString},
			{name: "address", flag: "address", kind: fieldString},
		},
	},
	{
		name: "deals", singular: "deal", paramKey: "deal",
		ops: opList | opShow | opCreate | opUpdate | opDelete,
		fields: []fieldSpec{
			{name: "name", flag: "name", kind: fieldString},
			{name: "stage", flag: "stage", kind: fieldString},
			{name: "value_cents", flag: "value-cents", kind: fieldInt},
			{name: "expected_close_on", flag: "expected-close-on", kind: fieldString},
			{name: "company_id", flag: "company-id", kind: fieldInt},
			{name: "contact_id", flag: "contact-id", kind: fieldInt},
			{name: "owner_id", flag: "owner-id", kind: fieldInt},
		},
	},
	{
		name: "invoices", singular: "invoice", paramKey: "invoice",
		ops: opList | opShow,
	},
	{
		name: "projects", singular: "project", paramKey: "project",
		ops: opList | opShow | opCreate | opUpdate | opDelete,
		fields: []fieldSpec{
			{name: "name", flag: "name", kind: fieldString},
			{name: "status", flag: "status", kind: fieldString},
			{name: "description", flag: "description", kind: fieldString},
			{name: "due_on", flag: "due-on", kind: fieldString},
			{name: "company_id", flag: "company-id", kind: fieldInt},
			{name: "deal_id", flag: "deal-id", kind: fieldInt},
		},
	},
	{
		name: "tasks", singular: "task", paramKey: "task",
		ops: opList | opShow | opCreate | opUpdate | opDelete,
		fields: []fieldSpec{
			{name: "title", flag: "title", kind: fieldString},
			{name: "status", flag: "status", kind: fieldString},
			{name: "description", flag: "description", kind: fieldString},
			{name: "due_on", flag: "due-on", kind: fieldString},
			{name: "project_id", flag: "project-id", kind: fieldInt},
			{name: "assignee_id", flag: "assignee-id", kind: fieldInt},
		},
	},
}
