// Command work is the Work CLI: one binary covering the whole public API.
// The command table (generated.go) is generated by bin/docs from the same
// contract-tested OpenAPI spec the server answers, so the CLI cannot drift
// from what the server does. Everything here is a thin client plus output
// formatting — no business logic, by design (AGENTS.md, "API, CLI and
// agents").
package main

import (
	"fmt"
	"io"
	"os"
	"strings"
)

// version is stamped at build time:
//
//	go build -ldflags "-X main.version=1.0.0"
//
// bin/build-cli does this for release archives.
var version = "dev"

func main() {
	os.Exit(run(os.Args[1:], os.Stdin, os.Stdout, os.Stderr, isTerminal(os.Stdout)))
}

func isTerminal(f *os.File) bool {
	info, err := f.Stat()
	return err == nil && info.Mode()&os.ModeCharDevice != 0
}

// Exit codes: 0 success, 1 API or runtime failure, 2 misuse (unknown
// command, bad flags) — so a script can tell "the server refused" apart
// from "you asked for something that does not exist".
func run(args []string, stdin io.Reader, stdout, stderr io.Writer, tty bool) int {
	global, rest, err := parseGlobalFlags(args)
	global.tty = tty
	if err != nil {
		fmt.Fprintf(stderr, "work: %v\n", err)
		return 2
	}

	switch {
	case global.version:
		fmt.Fprintf(stdout, "work %s\n", version)
		return 0
	case len(rest) == 0 || global.help:
		printHelp(stdout)
		return 0
	}

	switch rest[0] {
	case "help":
		// `work help contacts` answers with that resource's usage; bare
		// `work help` with the whole surface.
		if len(rest) > 1 {
			if spec, ok := findResource(rest[1]); ok {
				printResourceHelp(stdout, spec)
				return 0
			}
			fmt.Fprintf(stderr, "work: unknown resource %q — run `work help` for the list.\n", rest[1])
			return 2
		}
		printHelp(stdout)
		return 0
	case "version":
		fmt.Fprintf(stdout, "work %s\n", version)
		return 0
	case "auth":
		return runAuth(global, rest[1:], ui{stdin: stdin, stdout: stdout, stderr: stderr, tty: tty, format: global.effectiveFormat()})
	}

	spec, ok := findResource(rest[0])
	if !ok {
		fmt.Fprintf(stderr, "work: unknown resource %q — run `work help` for the list.\n", rest[0])
		return 2
	}

	// Help never needs a credential: `work contacts --help` and
	// `work contacts create -h` answer from the command table before a
	// client — and therefore a token — exists at all. A verb the resource
	// does not have is still a refusal, never usage for an endpoint that
	// isn't there.
	if len(rest) > 1 && wantsHelp(rest[1:]) {
		verb := rest[1]
		switch {
		case strings.HasPrefix(verb, "-"):
			printResourceHelp(stdout, spec)
			return 0
		case spec.supports(verb):
			printCommandUsage(stdout, spec, verb)
			return 0
		default:
			fmt.Fprintf(stderr, "work: %s has no %q in the API — its verbs are: %s.\n",
				spec.name, verb, strings.Join(spec.verbs(), ", "))
			return 2
		}
	}
	if len(rest) == 1 {
		fmt.Fprintf(stderr, "work: %s needs a verb — one of: %s.\n", spec.name, strings.Join(spec.verbs(), ", "))
		return 2
	}

	c, err := global.client()
	if err != nil {
		fmt.Fprintf(stderr, "work: %v\n", err)
		return 1
	}

	code := runResource(c, spec, rest[1:], ui{stdin: stdin, stdout: stdout, stderr: stderr, tty: tty, format: global.effectiveFormat()})
	if code == 0 && tty {
		maybeNotifyUpdate(stderr)
	}
	return code
}
